<?php


namespace frontend\controllers;


use yii\filters\AccessControl;
use yii\web\Controller;

class MainController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['login','confirm','registration','cart','category','view'],
                        'allow' => true,
                    ],
                    [

                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function init()
    {
        $this->view->title = 'Wolmart e-commerce';
        parent::init(); // TODO: Change the autogenerated stub
    }
}