<?php

namespace common\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "shop_order".
 *
 * @property int $id
 * @property int|null $user_id
 * @property string $fio
 * @property string $phone
 * @property int|null $district_id
 * @property int $region_id
 * @property string $address
 * @property int|null $delivery
 * @property string|null $created_date
 * @property int|null $status
 * @property string $total_sum
 * @property string $total_products_count
 */
class ShopOrder extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'shop_order';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id', 'district_id', 'region_id', 'delivery', 'status'], 'integer'],
            [['fio', 'phone', 'region_id', 'address', 'total_sum', 'total_products_count'], 'required'],
            [['created_date'], 'safe'],
            [['fio', 'address', 'total_sum', 'total_products_count'], 'string', 'max' => 255],
            [['phone'], 'string', 'max' => 20],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'fio' => 'Full name',
            'phone' => 'Phone',
            'district_id' => 'District',
            'region_id' => 'Region',
            'address' => 'Address',
            'delivery' => 'Delivery',
            'created_date' => 'Created Date',
            'status' => 'Status',
            'total_sum' => 'Total Sum',
            'total_products_count' => 'Total Products Count',
        ];
    }
    public function beforeSave($insert)
    {
        $this->created_date = date('Y-m-d H:i:s');
        $this->delivery = 0;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    public function afterSave($insert, $changedAttributes)
    {
        foreach ($_SESSION['cart']['products'] as $key=>$product){
            $orderProduct = new OrderProducts();
            $orderProduct->order_id = $this->id;
            $orderProduct->product_id = $key;
            $orderProduct->quantity = $product['count'];
            $orderProduct->sum = $product['price'];
            if($orderProduct->save()){

            }
        }
        unset($_SESSION);
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
    public function getDistricts(){
        return ArrayHelper::map(Districts::find()->all(),'id','name');
    }
    public function getRegions(){
        return ArrayHelper::map(Regions::find()->all(),'id','name');
    }
}
